### ISSUE TITLE
默认配置能上youtube但是不能上google.com

### ISSUE THREAD

**Issue by winloud** [frainzy1477/clashr#6]
只订阅了ssr链接，客户端选的是订阅配置，首页概览如下显示：

`

国外网IP  : 正在检查... | 谷歌网 : 超时 | Youtube  : 正常 | Github  : 正常
-- | -- | -- | --

`

**Comment by winloud** [comment]
大概是DNS域名解析的问题，什么也没动，吃个中饭回来就正常了。。。

**Comment by winloud** [comment]
又抽风了，大佬给指导一下，改怎么弄？我觉得是DNS的问题，有搜到说装DNS-Forwarder来解决，我先试试看，一会来反馈。

**Comment by frainzy1477** [comment]
你试试firefox, 有时候chorme一样,可能是你的DNS的问题

```
experimental:
  ignore-resolve-fail: true

#authentication:
# - "user1:pass1"

# hosts:
#   '*.clash.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'
 
dns:
 enable: true
 listen: 0.0.0.0:5300
 enhanced-mode: redir-host
 nameserver: 
  - 119.29.29.29 
  - 114.114.114.114    
  - tls://dns.rubyfish.cn:853
  - https://dns.google/dns-query
  - https://1.1.1.1/dns-query
fallback:
  - tls://dns.rubyfish.cn:853
  - tcp://1.1.1.1
  - tcp://8.8.8.8
fallback-filter:
  geoip: true
  ipcidr:
    - 240.0.0.0/4 
```
